CURRENT NORTH
Select first point to define North
Select a point that is due north of the point just entered
Enter sun azimuth: 
Enter sun altitude: 
Enter function key label: 
Function key label
 (Azimuth=
 , Altitude=
Enter description: 
creating folder
Error updating existing setting
saving to file
closing file
Sun Postion saved
opening saved sunpos file
reading function key label
reading ln after lbl
reading function key message
reading ln after msg
reading 
Error reading saved azimuth
reading ln after azimuth
reading altitude
Error reading saved altitude
closing file
Select Sun Position (Altitude, Azimuth)
$ set as sun position
Enter filter to apply to displayed saved settings: 
Enter height of z plane: 
Select polygon to cast shadows onto
Please select a surface polygon with 36 or less sides
Selected point too far from a suitable polygon
All entities
3D Surfaces & Solids, 
Slabs, Polygons, Blocks, 
Curved 3D surfaces & solids, 
2D & 3D Lines, 
2D Lines, 
3D Lines, 
Polylines, 
Symbols, 
Text, 
Dimensions, 
no entity types specified
Choose entity types to cast shadows of
Choose Selection Set to use for Shadow Entities
add to Selection Set
remove from Selection Set
  Created:
Calculating surface and sun position
Sorry: an unexpected error has occurred
Cannot cast Shadows|(Suns rays are parallel to surface)
Creating Symbol
Shadows created for $ entities
Shadow creation limit of 32,750|entities was reached.
No shadows cast on this surface by entity(s)
Polygon with more than 36 sides was processed - shadow may not be correct
Unexpected result casting shadows:|  Excessive iterations in trim loop.||Interim Shadow lines have been shown|temporarily on drawing (refresh to remove)
Please dismiss this message and take a screen dump and send the dump|to the author (dhsoftware1@gmail.com) together with any other|details you are willing to share (e.g. drawing file)|Thank you
No entity types have been specified for shadow casting.||Go to Shadow Entities menu (F5) and then select Ent|Types (S8) to specify types of entities to cast shadows.|
Setting surface to a horizontal plane at $
Dismiss
Show Instruction Manual
|This software is distributed free of charge and WITHOUT WARRANTY. You may distribute it to others provided that you distribute the complete unaltered installation file provided by me at the dhsoftware.com.au web site, and that you do so free of charge (This includes not  charging for distribution media and not charging for any accompanying software that is on the same media or contained in the same download or distribution file). 
If you wish to make any charge at all you need to obtain specific permission from me.
Whilst it is free (or because of this) I would like and expect that if you can think of any improvements or spot any bugs (or even spelling or formatting errors in the documentation) that you would let me know.  Your feedback will help with future development of the macro.
You are under no obligation to pay for this free macro. But if you find it useful a contribution towards the cost of its development and distribution would be appreciated. A suggested contribution amount for this macro is $40 AUD. A contribution may be made using the link at the left below.
Sun Position Calculator
Latitude
+ve for North, -ve for South
Longitude
+ve for East, -ve for West
Latitude/Longitude Entry Format
Degrees.Minutes.Seconds
Decimal Degrees
Time Zone
Place Name
Abbreviation
Calculate
Exit
Help
Export to Macro
About
Daylight Saving
sun too low
Al: 
Az: 
Time Zone must be selected
Longitude must be entered
Max longitude allowed is 180
Invalid format for longitude
Latitude must be entered
Max latitude allowed is 89
Invalid format for latitude
Error creating Shad directory
Must Enter Place Abbreviation
Added to Saved Sun Positions && filter set
Nothing to Export (Have you calculated?)
Altitude && Azimuth transferred to Macro
Select highlight colour for entities
Entity Dash Pixels: 
Select highlight colour for surface
Surface Dash Pixels: 
Enter name of new or existing layer : 
$. Lyr=$, Clr=$
(current)
'Sun Position Calculator may take a few seconds to open ...'
Cast shadows on top surface of selected polygon
Cast shadows on selected polygon
Processing shadows ... please wait
NORTH
Active Layer
Enter new name for '$':
Layer Creation in Progress
